---
title: "RGL Perspective Plots"
author: "Paul Lewis"
date: "2024-07-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
require(gridExtra)
library(plotly)
```

Plot of simulated combinations of theta and lambda

```{r}
halftheta = c(__HALFTHETAVECTOR__)
T = c(__TVECTOR__)
numdeep = c(__NUMDEEP__)
maxdeep = c(__MAXDEEP__)
nspecies = __NSPECIES__
smcmean   <- c(__SMCBHVMEANS__)

plot(halftheta, T, type="p", pch=19, main="Simulation conditions", xlab="theta/2", ylab="T")
```
Set colors for plots

```{r}
bgcolor <- "cornsilk"
planecolor <- "ghostwhite"
surfcolor <- "red"
```

Set up values used for the x-axis and y-axis of the grid

```{r}
halftheta_vals <- unique(halftheta)
cat("halftheta_vals:\n")
halftheta_vals
ncols <- length(halftheta_vals)

T_vals <- unique(T)
cat("T_vals:\n")
T_vals
nrows <- length(T_vals)
```

Get BHV info content.

```{r}
info <- c(__SMC_INFO_BHV__)
info <- 100 * info
t_ratio <- T / halftheta
infodf <- data.frame(halftheta, T, info, smcmean, t_ratio)
proportiondeep <- numdeep/maxdeep
```

Contour plot showing number of deep coalescences

```{r}
v <- ggplot(infodf, aes(halftheta, T, z = proportiondeep))
v + geom_contour_filled(breaks=c(0.0,0.2,0.4,0.6,0.8,1.0)) + labs(x=expression(theta/2))
```

3D plot labeled by T / halftheta

```{r}
library(plotly)

info_axis <- list(
  nticks = 10,
  range = c(-10,100),
  title = "information"
)

accuracy_axis <- list(
  nticks = 0.2,
  range = c(0,0.3),
  title = "inaccuracy"
)

tratio_axis <- list(
  nticks = 4,
  range = c(0,12),
  title = "t_ratio"
)

scale_bar <- list(
  title = "number of deep coalescences"
) 

fig <- plot_ly(infodf, x = ~info, y = ~smcmean, z = ~t_ratio, size=1, mode = "markers", color=proportiondeep)
fig <- fig %>% layout(scene = list(xaxis=info_axis,yaxis=accuracy_axis,zaxis=tratio_axis, annotations = scale_bar))

```
