---
title: "RGL Perspective Plots"
author: "Paul Lewis"
date: "2024-07-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
require(gridExtra)
library(plotly)
```

Plot of simulated combinations of theta and lambda

```{r}
halftheta = c(__HALFTHETAVECTOR__)
T = c(__TVECTOR__)
numdeep = c(__NUMDEEP__)
maxdeep = c(__MAXDEEP__)
nspecies = __NSPECIES__
smcmean   <- c(__SMCRFMEANS__)

rf_max = (nspecies - 3) *2
smcmean <- smcmean/rf_max # scale rf to maximum

plot(halftheta, T, type="p", pch=19, main="Simulation conditions", xlab="theta/2", ylab="T")
```
Set colors for plots

```{r}
bgcolor <- "cornsilk"
planecolor <- "ghostwhite"
surfcolor <- "red"
```

Set up values used for the x-axis and y-axis of the grid

```{r}
halftheta_vals <- unique(halftheta)
cat("halftheta_vals:\n")
halftheta_vals
ncols <- length(halftheta_vals)

T_vals <- unique(T)
cat("T_vals:\n")
T_vals
nrows <- length(T_vals)
```

Get new info content.

```{r}
info <- c(__SMC_INFO__)
t_ratio <- T / halftheta
infodf <- data.frame(halftheta, T, info, smcmean, t_ratio)
proportiondeep <- numdeep/maxdeep
```

Get uncorrected info content.

```{r}
old_info <- c(__SMC_OLD_INFO__)
t_ratio <- T / halftheta
old_infodf <- data.frame(halftheta, T, old_info, smcmean, t_ratio)
```

Contour plot new info and uncorrected info

```{r}
min1 = round((min(info) / 5.0)) * 5.0 - 5.0 # round to nearest 5, then round down
max1 = round((max(info) / 5.0)) * 5.0 # round to nearest 5, then round up
break_vec = c()

min2 = round((min(old_info) / 5.0)) * 5.0 - 5.0 # round to nearest 5, then round down
max2 = round((max(old_info) / 5.0)) * 5.0 # round to nearest 5, then round up

min <- min(min1, min2)
max <- max(max1, max2)

# ensure break vec is the same for both plots

for (i in min:max) {
  if ((i %% 5.0) == 0) {
    if (i == max) {
      break_vec <- append(break_vec, i+0.1)
    }
    else {
      break_vec <- append(break_vec, i)
    }
  }
}

plot1 <- ggplot(infodf, aes(halftheta, T, z = info)) + geom_contour_filled(breaks=c(break_vec)) + labs(x=expression(theta/2))+
  scale_fill_viridis_d(drop = FALSE) + labs(title="new info")

plot2 <- ggplot(old_infodf, aes(halftheta, T, z = old_info)) + geom_contour_filled(breaks=c(break_vec)) + labs(x=expression(theta/2)) +
  scale_fill_viridis_d(drop = FALSE) + labs(title="uncorrected info")

# side by side plots
grid.arrange(plot1, plot2, ncol=2)

```

Contour plot showing number of deep coalescences

```{r}
v <- ggplot(infodf, aes(halftheta, T, z = proportiondeep))
v + geom_contour_filled(breaks=c(0.0,0.2,0.4,0.6,0.8,1.0)) + labs(x=expression(theta/2))
```

3D plot labeled by T / halftheta

```{r}
library(plotly)
fig <- plot_ly(infodf, x = ~info, y = ~smcmean, z = ~t_ratio, size=1, mode = "markers", color=proportiondeep)
fig 

```
