---
title: "RGL Perspective Plots"
author: "Paul Lewis"
date: "2024-07-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

Plot of simulated combinations of theta and lambda

```{r}
halftheta = c(__HALFTHETAVECTOR__)
T = c(__TVECTOR__)
numdeep = c(__NUMDEEP__)
maxdeep = c(__MAXDEEP__)
nspecies = __NSPECIES__
plot(halftheta, T, type="p", pch=19, main="Simulation conditions", xlab="theta/2", ylab="T")
```
Set colors for plots

```{r}
bgcolor <- "cornsilk"
planecolor <- "ghostwhite"
surfcolor <- "red"
```

Set up values used for the x-axis and y-axis of the grid

```{r}
halftheta_vals <- unique(halftheta)
cat("halftheta_vals:\n")
halftheta_vals
ncols <- length(halftheta_vals)

T_vals <- unique(T)
cat("T_vals:\n")
T_vals
nrows <- length(T_vals)
```

The rf-summary.txt and kf-summary.txt files are created by crunch.py

```{r}
smcmean   <- c(__SMCRFMEANS__)
beastmean <- c(__BEASTRFMEANS__)
smcminusbeast <- c(__SMC_MINUS_BEAST_RF__)
proportiondeep <- numdeep/maxdeep
rf <- data.frame(halftheta, T, smcmean, beastmean)
```

Contour plot SMC on top, BEAST on bottom. of zero delta RF plane

```{r}
v <- ggplot(rf, aes(halftheta, T, z = smcminusbeast))
v + geom_contour_filled(breaks=c(__CONTOUR_BREAKS__)) + labs(x=expression(theta/2))
```

Contour plot showing number of deep coalescences

```{r}
v <- ggplot(rf, aes(halftheta, T, z = proportiondeep))
v + geom_contour_filled(breaks=c(0.0,0.2,0.4,0.6,0.8,1.0)) + labs(x=expression(theta/2))
```

